name: SouSi

on:
#  push:
#    branches: [ master ]
  schedule:
    - cron: '5 4,12 * * *'

env:
  ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: requirements
      run: |
        pip3 install -r requirements.txt

    - name: Run
      run: |
        python3 cli.py sousi --end-page 2
